/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AuthLayoutRouteImport } from './routes/_auth/layout'
import { Route as AppLayoutRouteImport } from './routes/_app/layout'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AppProtectedLayoutRouteImport } from './routes/_app/_protected/layout'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as AuthPasswordResetRouteImport } from './routes/_auth/password.reset'
import { Route as AuthAuthErrorRouteImport } from './routes/_auth/auth.error'
import { Route as AppPublicContactRouteImport } from './routes/_app/_public/contact'
import { Route as AppPublicAboutRouteImport } from './routes/_app/_public/about'
import { Route as AppProtectedSettingsRouteImport } from './routes/_app/_protected/settings'
import { Route as AppProtectedProfileRouteImport } from './routes/_app/_protected/profile'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLayoutRoute = AppLayoutRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AppProtectedLayoutRoute = AppProtectedLayoutRouteImport.update({
  id: '/_protected',
  getParentRoute: () => AppLayoutRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPasswordResetRoute = AuthPasswordResetRouteImport.update({
  id: '/password/reset',
  path: '/password/reset',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthAuthErrorRoute = AuthAuthErrorRouteImport.update({
  id: '/auth/error',
  path: '/auth/error',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AppPublicContactRoute = AppPublicContactRouteImport.update({
  id: '/_public/contact',
  path: '/contact',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppPublicAboutRoute = AppPublicAboutRouteImport.update({
  id: '/_public/about',
  path: '/about',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppProtectedSettingsRoute = AppProtectedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppProtectedLayoutRoute,
} as any)
const AppProtectedProfileRoute = AppProtectedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppProtectedLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/$': typeof SplatRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/api/$': typeof ApiSplatRoute
  '/profile': typeof AppProtectedProfileRoute
  '/settings': typeof AppProtectedSettingsRoute
  '/about': typeof AppPublicAboutRoute
  '/contact': typeof AppPublicContactRoute
  '/auth/error': typeof AuthAuthErrorRoute
  '/password/reset': typeof AuthPasswordResetRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/$': typeof SplatRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/api/$': typeof ApiSplatRoute
  '/profile': typeof AppProtectedProfileRoute
  '/settings': typeof AppProtectedSettingsRoute
  '/about': typeof AppPublicAboutRoute
  '/contact': typeof AppPublicContactRoute
  '/auth/error': typeof AuthAuthErrorRoute
  '/password/reset': typeof AuthPasswordResetRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppLayoutRouteWithChildren
  '/_auth': typeof AuthLayoutRouteWithChildren
  '/$': typeof SplatRoute
  '/_app/_protected': typeof AppProtectedLayoutRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/api/$': typeof ApiSplatRoute
  '/_app/': typeof AppIndexRoute
  '/_app/_protected/profile': typeof AppProtectedProfileRoute
  '/_app/_protected/settings': typeof AppProtectedSettingsRoute
  '/_app/_public/about': typeof AppPublicAboutRoute
  '/_app/_public/contact': typeof AppPublicContactRoute
  '/_auth/auth/error': typeof AuthAuthErrorRoute
  '/_auth/password/reset': typeof AuthPasswordResetRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/login'
    | '/register'
    | '/api/$'
    | '/profile'
    | '/settings'
    | '/about'
    | '/contact'
    | '/auth/error'
    | '/password/reset'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/login'
    | '/register'
    | '/api/$'
    | '/profile'
    | '/settings'
    | '/about'
    | '/contact'
    | '/auth/error'
    | '/password/reset'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/$'
    | '/_app/_protected'
    | '/_auth/login'
    | '/_auth/register'
    | '/api/$'
    | '/_app/'
    | '/_app/_protected/profile'
    | '/_app/_protected/settings'
    | '/_app/_public/about'
    | '/_app/_public/contact'
    | '/_auth/auth/error'
    | '/_auth/password/reset'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppLayoutRoute: typeof AppLayoutRouteWithChildren
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
  SplatRoute: typeof SplatRoute
  ApiSplatRoute: typeof ApiSplatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_app/_protected': {
      id: '/_app/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppProtectedLayoutRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/password/reset': {
      id: '/_auth/password/reset'
      path: '/password/reset'
      fullPath: '/password/reset'
      preLoaderRoute: typeof AuthPasswordResetRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/auth/error': {
      id: '/_auth/auth/error'
      path: '/auth/error'
      fullPath: '/auth/error'
      preLoaderRoute: typeof AuthAuthErrorRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_app/_public/contact': {
      id: '/_app/_public/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof AppPublicContactRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/_public/about': {
      id: '/_app/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AppPublicAboutRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/_protected/settings': {
      id: '/_app/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppProtectedSettingsRouteImport
      parentRoute: typeof AppProtectedLayoutRoute
    }
    '/_app/_protected/profile': {
      id: '/_app/_protected/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProtectedProfileRouteImport
      parentRoute: typeof AppProtectedLayoutRoute
    }
  }
}

interface AppProtectedLayoutRouteChildren {
  AppProtectedProfileRoute: typeof AppProtectedProfileRoute
  AppProtectedSettingsRoute: typeof AppProtectedSettingsRoute
}

const AppProtectedLayoutRouteChildren: AppProtectedLayoutRouteChildren = {
  AppProtectedProfileRoute: AppProtectedProfileRoute,
  AppProtectedSettingsRoute: AppProtectedSettingsRoute,
}

const AppProtectedLayoutRouteWithChildren =
  AppProtectedLayoutRoute._addFileChildren(AppProtectedLayoutRouteChildren)

interface AppLayoutRouteChildren {
  AppProtectedLayoutRoute: typeof AppProtectedLayoutRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppPublicAboutRoute: typeof AppPublicAboutRoute
  AppPublicContactRoute: typeof AppPublicContactRoute
}

const AppLayoutRouteChildren: AppLayoutRouteChildren = {
  AppProtectedLayoutRoute: AppProtectedLayoutRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppPublicAboutRoute: AppPublicAboutRoute,
  AppPublicContactRoute: AppPublicContactRoute,
}

const AppLayoutRouteWithChildren = AppLayoutRoute._addFileChildren(
  AppLayoutRouteChildren,
)

interface AuthLayoutRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthAuthErrorRoute: typeof AuthAuthErrorRoute
  AuthPasswordResetRoute: typeof AuthPasswordResetRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthAuthErrorRoute: AuthAuthErrorRoute,
  AuthPasswordResetRoute: AuthPasswordResetRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppLayoutRoute: AppLayoutRouteWithChildren,
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
  SplatRoute: SplatRoute,
  ApiSplatRoute: ApiSplatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
