/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AuthLayoutRouteImport } from './routes/_auth/layout'
import { Route as AppLayoutRouteImport } from './routes/_app/layout'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AppProtectedLayoutRouteImport } from './routes/_app/_protected/layout'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe.webhook'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as AuthAuthErrorRouteImport } from './routes/_auth/auth.error'
import { Route as AppProtectedTestRouteImport } from './routes/_app/_protected/test'
import { Route as AppPublicShopIndexRouteImport } from './routes/_app/_public/shop/index'
import { Route as AppPublicCheckoutIndexRouteImport } from './routes/_app/_public/checkout.index'
import { Route as AppPublicShopCategoryRouteImport } from './routes/_app/_public/shop/$category'
import { Route as AppPublicCheckoutSuccessRouteImport } from './routes/_app/_public/checkout.success'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLayoutRoute = AppLayoutRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AppProtectedLayoutRoute = AppProtectedLayoutRouteImport.update({
  id: '/_protected',
  getParentRoute: () => AppLayoutRoute,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAuthErrorRoute = AuthAuthErrorRouteImport.update({
  id: '/auth/error',
  path: '/auth/error',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AppProtectedTestRoute = AppProtectedTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => AppProtectedLayoutRoute,
} as any)
const AppPublicShopIndexRoute = AppPublicShopIndexRouteImport.update({
  id: '/_public/shop/',
  path: '/shop/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppPublicCheckoutIndexRoute = AppPublicCheckoutIndexRouteImport.update({
  id: '/_public/checkout/',
  path: '/checkout/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppPublicShopCategoryRoute = AppPublicShopCategoryRouteImport.update({
  id: '/_public/shop/$category',
  path: '/shop/$category',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppPublicCheckoutSuccessRoute =
  AppPublicCheckoutSuccessRouteImport.update({
    id: '/_public/checkout/success',
    path: '/checkout/success',
    getParentRoute: () => AppLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/$': typeof SplatRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/api/$': typeof ApiSplatRoute
  '/test': typeof AppProtectedTestRoute
  '/auth/error': typeof AuthAuthErrorRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/checkout/success': typeof AppPublicCheckoutSuccessRoute
  '/shop/$category': typeof AppPublicShopCategoryRoute
  '/checkout/': typeof AppPublicCheckoutIndexRoute
  '/shop/': typeof AppPublicShopIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/$': typeof SplatRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/api/$': typeof ApiSplatRoute
  '/test': typeof AppProtectedTestRoute
  '/auth/error': typeof AuthAuthErrorRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/checkout/success': typeof AppPublicCheckoutSuccessRoute
  '/shop/$category': typeof AppPublicShopCategoryRoute
  '/checkout': typeof AppPublicCheckoutIndexRoute
  '/shop': typeof AppPublicShopIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppLayoutRouteWithChildren
  '/_auth': typeof AuthLayoutRouteWithChildren
  '/$': typeof SplatRoute
  '/_app/_protected': typeof AppProtectedLayoutRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/api/$': typeof ApiSplatRoute
  '/_app/': typeof AppIndexRoute
  '/_app/_protected/test': typeof AppProtectedTestRoute
  '/_auth/auth/error': typeof AuthAuthErrorRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/_app/_public/checkout/success': typeof AppPublicCheckoutSuccessRoute
  '/_app/_public/shop/$category': typeof AppPublicShopCategoryRoute
  '/_app/_public/checkout/': typeof AppPublicCheckoutIndexRoute
  '/_app/_public/shop/': typeof AppPublicShopIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/login'
    | '/register'
    | '/api/$'
    | '/test'
    | '/auth/error'
    | '/api/auth/$'
    | '/api/stripe/webhook'
    | '/checkout/success'
    | '/shop/$category'
    | '/checkout/'
    | '/shop/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/login'
    | '/register'
    | '/api/$'
    | '/test'
    | '/auth/error'
    | '/api/auth/$'
    | '/api/stripe/webhook'
    | '/checkout/success'
    | '/shop/$category'
    | '/checkout'
    | '/shop'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/$'
    | '/_app/_protected'
    | '/_auth/login'
    | '/_auth/register'
    | '/api/$'
    | '/_app/'
    | '/_app/_protected/test'
    | '/_auth/auth/error'
    | '/api/auth/$'
    | '/api/stripe/webhook'
    | '/_app/_public/checkout/success'
    | '/_app/_public/shop/$category'
    | '/_app/_public/checkout/'
    | '/_app/_public/shop/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppLayoutRoute: typeof AppLayoutRouteWithChildren
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
  SplatRoute: typeof SplatRoute
  ApiSplatRoute: typeof ApiSplatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_app/_protected': {
      id: '/_app/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppProtectedLayoutRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/auth/error': {
      id: '/_auth/auth/error'
      path: '/auth/error'
      fullPath: '/auth/error'
      preLoaderRoute: typeof AuthAuthErrorRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_app/_protected/test': {
      id: '/_app/_protected/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof AppProtectedTestRouteImport
      parentRoute: typeof AppProtectedLayoutRoute
    }
    '/_app/_public/shop/': {
      id: '/_app/_public/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof AppPublicShopIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/_public/checkout/': {
      id: '/_app/_public/checkout/'
      path: '/checkout'
      fullPath: '/checkout/'
      preLoaderRoute: typeof AppPublicCheckoutIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/_public/shop/$category': {
      id: '/_app/_public/shop/$category'
      path: '/shop/$category'
      fullPath: '/shop/$category'
      preLoaderRoute: typeof AppPublicShopCategoryRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/_public/checkout/success': {
      id: '/_app/_public/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof AppPublicCheckoutSuccessRouteImport
      parentRoute: typeof AppLayoutRoute
    }
  }
}

interface AppProtectedLayoutRouteChildren {
  AppProtectedTestRoute: typeof AppProtectedTestRoute
}

const AppProtectedLayoutRouteChildren: AppProtectedLayoutRouteChildren = {
  AppProtectedTestRoute: AppProtectedTestRoute,
}

const AppProtectedLayoutRouteWithChildren =
  AppProtectedLayoutRoute._addFileChildren(AppProtectedLayoutRouteChildren)

interface AppLayoutRouteChildren {
  AppProtectedLayoutRoute: typeof AppProtectedLayoutRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppPublicCheckoutSuccessRoute: typeof AppPublicCheckoutSuccessRoute
  AppPublicShopCategoryRoute: typeof AppPublicShopCategoryRoute
  AppPublicCheckoutIndexRoute: typeof AppPublicCheckoutIndexRoute
  AppPublicShopIndexRoute: typeof AppPublicShopIndexRoute
}

const AppLayoutRouteChildren: AppLayoutRouteChildren = {
  AppProtectedLayoutRoute: AppProtectedLayoutRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppPublicCheckoutSuccessRoute: AppPublicCheckoutSuccessRoute,
  AppPublicShopCategoryRoute: AppPublicShopCategoryRoute,
  AppPublicCheckoutIndexRoute: AppPublicCheckoutIndexRoute,
  AppPublicShopIndexRoute: AppPublicShopIndexRoute,
}

const AppLayoutRouteWithChildren = AppLayoutRoute._addFileChildren(
  AppLayoutRouteChildren,
)

interface AuthLayoutRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthAuthErrorRoute: typeof AuthAuthErrorRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthAuthErrorRoute: AuthAuthErrorRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppLayoutRoute: AppLayoutRouteWithChildren,
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
  SplatRoute: SplatRoute,
  ApiSplatRoute: ApiSplatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
